-- GENERATED by assets/alphabet3d/gen_glyphs_lua.js -- do not hand-edit.
-- Metrics are measured off the actual exported meshes, so sign layout in game
-- matches the props exactly rather than guessing at advance widths.

local Glyphs = {}

--- Cap height of the source models, in metres. Sign scale 1.0 == 1 m capitals.
Glyphs.CAP = 1
--- Front-to-back depth of the source models, in metres (bevel skirt not included).
Glyphs.DEPTH = 0.12
--- Bevel radius in metres: adds this beyond DEPTH, and above/below the cap line.
Glyphs.BEVEL = 0.01
--- Default gap between letters, in cap-height units.
Glyphs.TRACKING = 0.12
--- Advance width of a space character, in cap-height units.
Glyphs.SPACE = 0.35

--- Palette colour names. The index into this list IS the model's tint index, so
--- the order here must match the row order of textures/alphabet_tint.dds.
Glyphs.COLOURS = { 'white', 'red', 'orange', 'amber', 'yellow', 'green', 'cyan', 'blue', 'purple', 'pink' }

--- Colour name -> tint index (0-based, unlike COLOURS which is a Lua 1-based list).
Glyphs.TINT = {
    ['white'] = 0,
    ['red'] = 1,
    ['orange'] = 2,
    ['amber'] = 3,
    ['yellow'] = 4,
    ['green'] = 5,
    ['cyan'] = 6,
    ['blue'] = 7,
    ['purple'] = 8,
    ['pink'] = 9,
}

--- char -> { model = streamed model name (only the finish tag is appended),
---           w = advance width, top/bot = extent above/below the baseline }
--- All measurements are in cap-height units, so they scale with the sign.
--- Keys are raw UTF-8 byte strings, so multi-byte symbols must be looked up by
--- whole character -- see the utf8-aware iteration in shared/sign.lua.
Glyphs.META = {
    ['A'] = { model = 'sd_a3d_ua', w = 1.1523, top = 1.01, bot = -0.01 },
    ['B'] = { model = 'sd_a3d_ub', w = 0.9372, top = 1.01, bot = -0.01 },
    ['C'] = { model = 'sd_a3d_uc', w = 0.9784, top = 1.0272, bot = -0.0272 },
    ['D'] = { model = 'sd_a3d_ud', w = 1.0257, top = 1.01, bot = -0.01 },
    ['E'] = { model = 'sd_a3d_ue', w = 0.7943, top = 1.01, bot = -0.01 },
    ['F'] = { model = 'sd_a3d_uf', w = 0.7757, top = 1.01, bot = -0.01 },
    ['G'] = { model = 'sd_a3d_ug', w = 0.9929, top = 1.0272, bot = -0.0272 },
    ['H'] = { model = 'sd_a3d_uh', w = 0.9371, top = 1.01, bot = -0.01 },
    ['I'] = { model = 'sd_a3d_ui', w = 0.2514, top = 1.01, bot = -0.01 },
    ['J'] = { model = 'sd_a3d_uj', w = 0.7089, top = 1.01, bot = -0.0272 },
    ['K'] = { model = 'sd_a3d_uk', w = 0.9849, top = 1.01, bot = -0.01 },
    ['L'] = { model = 'sd_a3d_ul', w = 0.7529, top = 1.01, bot = -0.01 },
    ['M'] = { model = 'sd_a3d_um', w = 1.1472, top = 1.01, bot = -0.01 },
    ['N'] = { model = 'sd_a3d_un', w = 0.9371, top = 1.01, bot = -0.01 },
    ['O'] = { model = 'sd_a3d_uo', w = 1.1143, top = 1.0272, bot = -0.0272 },
    ['P'] = { model = 'sd_a3d_up', w = 0.8872, top = 1.01, bot = -0.01 },
    ['Q'] = { model = 'sd_a3d_uq', w = 1.1679, top = 1.0272, bot = -0.24 },
    ['R'] = { model = 'sd_a3d_ur', w = 0.9148, top = 1.01, bot = -0.01 },
    ['S'] = { model = 'sd_a3d_us', w = 0.854, top = 1.0271, bot = -0.0271 },
    ['T'] = { model = 'sd_a3d_ut', w = 0.8914, top = 1.01, bot = -0.01 },
    ['U'] = { model = 'sd_a3d_uu', w = 0.9257, top = 1.01, bot = -0.0272 },
    ['V'] = { model = 'sd_a3d_uv', w = 1.1233, top = 1.01, bot = -0.01 },
    ['W'] = { model = 'sd_a3d_uw', w = 1.6262, top = 1.01, bot = -0.01 },
    ['X'] = { model = 'sd_a3d_ux', w = 1.0506, top = 1.01, bot = -0.01 },
    ['Y'] = { model = 'sd_a3d_uy', w = 1.0425, top = 1.01, bot = -0.01 },
    ['Z'] = { model = 'sd_a3d_uz', w = 0.8943, top = 1.01, bot = -0.01 },
    ['a'] = { model = 'sd_a3d_la', w = 0.75, top = 0.79, bot = -0.0215 },
    ['b'] = { model = 'sd_a3d_lb', w = 0.8572, top = 1.07, bot = -0.0215 },
    ['c'] = { model = 'sd_a3d_lc', w = 0.7966, top = 0.79, bot = -0.0214 },
    ['d'] = { model = 'sd_a3d_ld', w = 0.8572, top = 1.07, bot = -0.0215 },
    ['e'] = { model = 'sd_a3d_le', w = 0.83, top = 0.79, bot = -0.0214 },
    ['f'] = { model = 'sd_a3d_lf', w = 0.6079, top = 1.0814, bot = -0.01 },
    ['g'] = { model = 'sd_a3d_lg', w = 0.87, top = 0.79, bot = -0.2986 },
    ['h'] = { model = 'sd_a3d_lh', w = 0.8057, top = 1.07, bot = -0.01 },
    ['i'] = { model = 'sd_a3d_li', w = 0.2972, top = 1.1343, bot = -0.01 },
    ['j'] = { model = 'sd_a3d_lj', w = 0.5181, top = 1.1343, bot = -0.2986 },
    ['k'] = { model = 'sd_a3d_lk', w = 0.8735, top = 1.07, bot = -0.01 },
    ['l'] = { model = 'sd_a3d_ll', w = 0.2429, top = 1.07, bot = -0.01 },
    ['m'] = { model = 'sd_a3d_lm', w = 1.3186, top = 0.79, bot = -0.01 },
    ['n'] = { model = 'sd_a3d_ln', w = 0.8057, top = 0.79, bot = -0.01 },
    ['o'] = { model = 'sd_a3d_lo', w = 0.8643, top = 0.79, bot = -0.0214 },
    ['p'] = { model = 'sd_a3d_lp', w = 0.8572, top = 0.79, bot = -0.2871 },
    ['q'] = { model = 'sd_a3d_lq', w = 0.8572, top = 0.79, bot = -0.2871 },
    ['r'] = { model = 'sd_a3d_lr', w = 0.4971, top = 0.7909, bot = -0.01 },
    ['s'] = { model = 'sd_a3d_ls', w = 0.7186, top = 0.79, bot = -0.0214 },
    ['t'] = { model = 'sd_a3d_lt', w = 0.6094, top = 0.9486, bot = -0.0214 },
    ['u'] = { model = 'sd_a3d_lu', w = 0.7986, top = 0.7786, bot = -0.0214 },
    ['v'] = { model = 'sd_a3d_lv', w = 0.9073, top = 0.7786, bot = -0.01 },
    ['w'] = { model = 'sd_a3d_lw', w = 1.3642, top = 0.7786, bot = -0.01 },
    ['x'] = { model = 'sd_a3d_lx', w = 0.8789, top = 0.7786, bot = -0.01 },
    ['y'] = { model = 'sd_a3d_ly', w = 0.9078, top = 0.7786, bot = -0.2986 },
    ['z'] = { model = 'sd_a3d_lz', w = 0.7057, top = 0.7786, bot = -0.01 },
    ['0'] = { model = 'sd_a3d_d0', w = 0.8772, top = 1.0272, bot = -0.0272 },
    ['1'] = { model = 'sd_a3d_d1', w = 0.4514, top = 1.01, bot = -0.01 },
    ['2'] = { model = 'sd_a3d_d2', w = 0.8261, top = 1.0272, bot = -0.01 },
    ['3'] = { model = 'sd_a3d_d3', w = 0.8188, top = 1.01, bot = -0.0271 },
    ['4'] = { model = 'sd_a3d_d4', w = 0.9471, top = 1.01, bot = -0.01 },
    ['5'] = { model = 'sd_a3d_d5', w = 0.8202, top = 1.01, bot = -0.0271 },
    ['6'] = { model = 'sd_a3d_d6', w = 0.8458, top = 1.0272, bot = -0.0272 },
    ['7'] = { model = 'sd_a3d_d7', w = 0.8214, top = 1.01, bot = -0.01 },
    ['8'] = { model = 'sd_a3d_d8', w = 0.8629, top = 1.0272, bot = -0.0272 },
    ['9'] = { model = 'sd_a3d_d9', w = 0.8458, top = 1.0272, bot = -0.0272 },
    ['.'] = { model = 'sd_a3d_speriod', w = 0.2972, top = 0.2758, bot = -0.0215 },
    [','] = { model = 'sd_a3d_scomma', w = 0.2958, top = 0.2757, bot = -0.23 },
    [':'] = { model = 'sd_a3d_scolon', w = 0.2972, top = 0.7886, bot = -0.0215 },
    [';'] = { model = 'sd_a3d_ssemi', w = 0.2972, top = 0.7886, bot = -0.23 },
    ['!'] = { model = 'sd_a3d_sexcl', w = 0.2944, top = 1.01, bot = -0.0215 },
    ['?'] = { model = 'sd_a3d_squest', w = 0.792, top = 1.0272, bot = -0.0215 },
    ['\''] = { model = 'sd_a3d_sapos', w = 0.2108, top = 1.01, bot = 0.5843 },
    ['"'] = { model = 'sd_a3d_sdquote', w = 0.505, top = 1.01, bot = 0.5843 },
    ['('] = { model = 'sd_a3d_slparen', w = 0.418, top = 1.07, bot = -0.2871 },
    [')'] = { model = 'sd_a3d_srparen', w = 0.4194, top = 1.07, bot = -0.2871 },
    ['['] = { model = 'sd_a3d_slbrack', w = 0.4071, top = 1.07, bot = -0.2871 },
    [']'] = { model = 'sd_a3d_srbrack', w = 0.4057, top = 1.07, bot = -0.2871 },
    ['{'] = { model = 'sd_a3d_slbrace', w = 0.4829, top = 1.07, bot = -0.2871 },
    ['}'] = { model = 'sd_a3d_srbrace', w = 0.4829, top = 1.07, bot = -0.2871 },
    ['<'] = { model = 'sd_a3d_slt', w = 0.7, top = 0.8659, bot = 0.1341 },
    ['>'] = { model = 'sd_a3d_sgt', w = 0.7, top = 0.8659, bot = 0.1341 },
    ['+'] = { model = 'sd_a3d_splus', w = 0.7, top = 0.84, bot = 0.16 },
    ['-'] = { model = 'sd_a3d_shyphen', w = 0.4243, top = 0.5014, bot = 0.3029 },
    ['='] = { model = 'sd_a3d_seq', w = 0.7, top = 0.7743, bot = 0.2257 },
    ['*'] = { model = 'sd_a3d_sstar', w = 0.6106, top = 1.07, bot = 0.4857 },
    ['/'] = { model = 'sd_a3d_sslash', w = 0.6982, top = 1.2129, bot = -0.1529 },
    ['\\'] = { model = 'sd_a3d_sbslash', w = 0.6982, top = 1.2129, bot = -0.1529 },
    ['%'] = { model = 'sd_a3d_spct', w = 1.1958, top = 1.0215, bot = -0.0215 },
    ['&'] = { model = 'sd_a3d_samp', w = 0.981, top = 1.0229, bot = -0.0316 },
    ['@'] = { model = 'sd_a3d_sat', w = 1.3872, top = 1.0243, bot = -0.3043 },
    ['#'] = { model = 'sd_a3d_shash', w = 0.9915, top = 1.01, bot = -0.01 },
    ['$'] = { model = 'sd_a3d_sdollar', w = 0.854, top = 1.1814, bot = -0.1814 },
    ['_'] = { model = 'sd_a3d_suscore', w = 0.7343, top = 0.01, bot = -0.1386 },
    ['|'] = { model = 'sd_a3d_spipe', w = 0.2243, top = 1.07, bot = -0.2871 },
    ['~'] = { model = 'sd_a3d_stilde', w = 0.7359, top = 0.6543, bot = 0.3485 },
    ['^'] = { model = 'sd_a3d_scaret', w = 0.7247, top = 0.8086, bot = 0.1914 },
    ['°'] = { model = 'sd_a3d_sdeg', w = 0.5215, top = 1.0229, bot = 0.5128 },
    ['€'] = { model = 'sd_a3d_seuro', w = 1.1159, top = 1.0272, bot = -0.0272 },
    ['£'] = { model = 'sd_a3d_spound', w = 0.9169, top = 1.0272, bot = -0.01 },
    ['¥'] = { model = 'sd_a3d_syen', w = 1.1307, top = 1.01, bot = -0.01 },
    ['¢'] = { model = 'sd_a3d_scent', w = 0.7965, top = 0.95, bot = -0.1814 },
    ['©'] = { model = 'sd_a3d_scopy', w = 1.0286, top = 1.0143, bot = -0.0143 },
    ['®'] = { model = 'sd_a3d_sreg', w = 1.0286, top = 1.0143, bot = -0.0143 },
    ['™'] = { model = 'sd_a3d_stm', w = 1.3915, top = 1.01, bot = 0.3971 },
    ['§'] = { model = 'sd_a3d_ssect', w = 0.7121, top = 1.0214, bot = -0.1643 },
    ['•'] = { model = 'sd_a3d_sbullet', w = 0.3772, top = 0.59, bot = 0.2086 },
    ['…'] = { model = 'sd_a3d_sellip', w = 1.0615, top = 0.2758, bot = -0.0215 },
    ['±'] = { model = 'sd_a3d_splusmin', w = 0.7, top = 0.9443, bot = -0.01 },
    ['×'] = { model = 'sd_a3d_stimes', w = 0.6279, top = 0.8186, bot = 0.1814 },
    ['÷'] = { model = 'sd_a3d_sdivide', w = 0.7, top = 0.9257, bot = 0.0742 },
    ['¼'] = { model = 'sd_a3d_squarter', w = 1.38, top = 1.01, bot = -0.01 },
    ['½'] = { model = 'sd_a3d_shalf', w = 1.35, top = 1.01, bot = -0.01 },
    ['¾'] = { model = 'sd_a3d_sthreeq', w = 1.4616, top = 1.01, bot = -0.01 },
    ['«'] = { model = 'sd_a3d_slaquo', w = 0.7559, top = 0.6743, bot = 0.0957 },
    ['»'] = { model = 'sd_a3d_sraquo', w = 0.7559, top = 0.6743, bot = 0.0957 },
    ['¡'] = { model = 'sd_a3d_siexcl', w = 0.2944, top = 0.79, bot = -0.23 },
    ['¿'] = { model = 'sd_a3d_siquest', w = 0.7919, top = 0.79, bot = -0.2457 },
    ['→'] = { model = 'sd_a3d_sarrr', w = 0.702, top = 0.7257, bot = 0.06 },
    ['←'] = { model = 'sd_a3d_sarrl', w = 0.702, top = 0.7271, bot = 0.0614 },
    ['↑'] = { model = 'sd_a3d_sarru', w = 0.66, top = 0.752, bot = 0.0443 },
    ['↓'] = { model = 'sd_a3d_sarrd', w = 0.6614, top = 0.7429, bot = 0.0351 },
    ['≤'] = { model = 'sd_a3d_sle', w = 0.7, top = 0.9442, bot = -0.01 },
    ['≥'] = { model = 'sd_a3d_sge', w = 0.7, top = 0.9442, bot = -0.01 },
    ['≠'] = { model = 'sd_a3d_sne', w = 0.7, top = 0.9314, bot = 0.0686 },
    ['∞'] = { model = 'sd_a3d_sinf', w = 1.2572, top = 0.8129, bot = 0.1871 },
    ['√'] = { model = 'sd_a3d_ssqrt', w = 1.1195, top = 1.07, bot = -0.2871 },
    ['¶'] = { model = 'sd_a3d_spara', w = 0.8615, top = 1.07, bot = -0.1529 },
    ['†'] = { model = 'sd_a3d_sdagger', w = 0.7786, top = 1.01, bot = -0.2871 },
    ['‡'] = { model = 'sd_a3d_sddagger', w = 0.7786, top = 1.01, bot = -0.2871 },
    ['µ'] = { model = 'sd_a3d_smicro', w = 0.8, top = 0.7786, bot = -0.2871 },
    ['ª'] = { model = 'sd_a3d_sordfa', w = 0.4958, top = 1.0814, bot = 0.5886 },
    ['º'] = { model = 'sd_a3d_sordfm', w = 0.5615, top = 1.0814, bot = 0.5886 },
}

--- Available finishes. "painted" is matte (default_tnt.sps); "neon" lights the
--- letter face with emissive_tnt.sps so it glows at night.
Glyphs.STYLES = { 'painted', 'neon' }

--- Resolve the streamed model name for a character.
--- Returns nil for characters the alphabet does not cover (so callers can skip them).
---
--- Colour is deliberately absent. Both finishes carry a tint palette, so a colour
--- is chosen per entity with SetObjectTextureVariation(ent, Glyphs.tint(colour))
--- rather than by picking a different model -- 258 models instead of 2580.
---@param char string single character
---@param style string|nil "painted" (default) or "neon"
---@return string|nil
function Glyphs.model(char, style)
    local meta = Glyphs.META[char]
    if not meta then return nil end
    return meta.model .. (style == 'neon' and '_neon' or '')
end

--- Palette colour name -> tint index, the value the game wants.
---@param colour string
---@return integer tint index, 0 (white) when the name is unknown
function Glyphs.tint(colour)
    return Glyphs.TINT[colour] or 0
end

--- Iterate `text` one whole character at a time, UTF-8 aware.
--- Byte-wise iteration would never match a multi-byte symbol key and would
--- silently strip every non-ASCII glyph.
---@param text string
---@return fun(): string|nil
function Glyphs.chars(text)
    local pos = 1
    return function()
        if pos > #text then return nil end
        local nextPos = utf8.offset(text, 2, pos) or (#text + 1)
        local c = text:sub(pos, nextPos - 1)
        pos = nextPos
        return c
    end
end

return Glyphs
